#!/bin.bash
echo "A long time ago in a galaxy far, far away....."

echo " "

echo "Star Wars Episode IV: A New Hope"

echo " "

echo "It is a period of civil war. Rebel spaceships, striking from a hidden base, have won their first victory against the evil Galactic Empire."

echo " "

echo "During the battle, Rebel spies managed to steal secret plans to the Empire's ultimate weapon, the DEATH STAR, an armored space station with enough power to destroy an entire planet."

echo " "

echo "Pursued by the Empire's sinister agents, Princess Leia races home aboard her starship, custodian of the stolen plans that can save her people and restore freedom to the galaxy...."
