#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed -i -e 's/#user www-data/user nginx/' -e 's/80/8080/g' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start

